extends Node3D
## LOBBY runtime controller. The room, props, lights, elevator and mirror are AUTHORED nodes
## in lobby.tscn (generated by tools/build_lobby.gd) — open the scene and move/tune anything.
## This script only does the live stuff: spawn players, drive the mirror camera, run the
## elevator-start + descent. Regenerate lobby.tscn with build_lobby.gd to reset the layout.

const PLAYER_SCENE := preload("res://scenes/entities/player.tscn")
const GAME := "res://scenes/game.tscn"
const MAIN_MENU := "res://scenes/main_menu.tscn"

@export var descend_time := 1.3        ## fade-to-black duration on descent
@export var start_radius := 2.4        ## how close to the elevator you must be to descend

var _players_node: Node3D
var _spawner: MultiplayerSpawner
var _start_pos := Vector3(0, 0, -7.6)
var _descending := false
var _pause: PauseMenu


func _ready() -> void:
	WPlayer.input_blocked = false
	VoiceManager.lobby_mode = true
	# The Mirror (scenes/mirror.tscn) is self-driving — it finds the player camera and renders
	# its own reflection. Nothing to wire here anymore.
	var sz := get_node_or_null("Elevator/StartZone") as Node3D
	if sz != null:
		_start_pos = sz.global_position
	_build_players()
	_build_hud()
	_build_toys()                # crowbar + fish to whack your friends with
	add_child(PSXPost.new())     # same retro look as gameplay (menus stay crisp)


# ---- players ----------------------------------------------------------------
func _build_players() -> void:
	_players_node = Node3D.new()
	_players_node.name = "Players"
	add_child(_players_node)
	var spawn := get_node_or_null("PlayerSpawn") as Node3D
	var base := spawn.global_position if spawn != null else Vector3(0, 0.4, 4.5)
	if not Net.is_active():
		var p := PLAYER_SCENE.instantiate() as WPlayer
		p.name = "Player"; p.blink_enabled = false; p.position = base
		_players_node.add_child(p)
		return
	_spawner = MultiplayerSpawner.new()
	_spawner.spawn_function = _spawn_player
	add_child(_spawner)
	_spawner.spawn_path = _players_node.get_path()
	if multiplayer.is_server():
		multiplayer.peer_connected.connect(func(id): _spawner.spawn(id))
		_spawner.spawn(1)
		for id in multiplayer.get_peers():
			_spawner.spawn(id)


func _spawn_player(data: Variant) -> Node:
	var p := PLAYER_SCENE.instantiate() as WPlayer
	p.name = str(data); p.blink_enabled = false
	var spawn := get_node_or_null("PlayerSpawn") as Node3D
	var base := spawn.global_position if spawn != null else Vector3(0, 0.4, 4.5)
	p.position = base + Vector3(randf_range(-3, 3), 0, 0)
	return p


func _local_player() -> WPlayer:
	for n in get_tree().get_nodes_in_group("players"):
		var p := n as WPlayer
		if p != null and (not Net.is_active() or p.is_multiplayer_authority()):
			return p
	return null


# ---- friendslop toys: grabbable melee weapons -------------------------------
func _build_toys() -> void:
	var spawn := get_node_or_null("PlayerSpawn") as Node3D
	var base := spawn.global_position if spawn != null else Vector3(0, 0.4, 4.5)
	base.y = 0.3
	_add_pickup("crowbar", "res://assets/psx2/Structures/rusty_crowbar_mx_1.glb", base + Vector3(-1.5, 0, -1.5))
	_add_pickup("fish", "res://assets/psx2/Props/fish_mx_1.glb", base + Vector3(1.5, 0, -1.5))
	_add_pickup("fish", "res://assets/psx2/Props/fish_mx_1.glb", base + Vector3(2.4, 0, -1.0))


func _add_pickup(kind: String, model: String, pos: Vector3) -> void:
	var pk := preload("res://scenes/item_pickup.tscn").instantiate() as ItemPickup
	pk.kind = kind
	pk.model_path = model
	pk.model_scale = 2.2 if kind == "fish" else 1.6
	pk.model_euler = Vector3(0, 0, 90)     # crowbar/fish are long on X -> stand them vertical
	pk.position = pos
	add_child(pk)


# ---- HUD --------------------------------------------------------------------
func _build_hud() -> void:
	var layer := CanvasLayer.new()
	add_child(layer)
	var hud := GameHUD.new()
	hud.player_fn = _local_player
	layer.add_child(hud)
	var l := Label.new()
	l.set_anchors_preset(Control.PRESET_TOP_WIDE)
	l.position = Vector2(0, 14)
	l.horizontal_alignment = HORIZONTAL_ALIGNMENT_CENTER
	l.add_theme_font_size_override("font_size", 14)
	l.add_theme_color_override("font_color", Color(0.8, 0.85, 0.95, 0.7))
	l.add_theme_color_override("font_outline_color", Color(0, 0, 0))
	l.add_theme_constant_override("outline_size", 5)
	l.text = "step into the elevator and press E to descend"
	layer.add_child(l)


# ---- start / descent --------------------------------------------------------
func _unhandled_input(event: InputEvent) -> void:
	if event.is_action_pressed("pause"):
		get_viewport().set_input_as_handled()
		if _pause != null and _pause.visible:
			_close_pause()
		else:
			_open_pause()


func _open_pause() -> void:
	if _pause == null:
		_pause = preload("res://scenes/ui/pause_menu.tscn").instantiate()
		add_child(_pause)
		_pause.resume_requested.connect(_close_pause)
	_pause.visible = true
	WPlayer.input_blocked = true                  # local only — others keep hanging out
	Input.mouse_mode = Input.MOUSE_MODE_VISIBLE


func _close_pause() -> void:
	if _pause != null:
		_pause.visible = false
	WPlayer.input_blocked = false
	Input.mouse_mode = Input.MOUSE_MODE_CAPTURED


func _physics_process(_delta: float) -> void:
	if not Net.is_authority():
		return
	for n in get_tree().get_nodes_in_group("players"):
		var p := n as WPlayer
		if p == null or p._downed:
			continue
		if p.consume_interact() and p.global_position.distance_to(_start_pos) <= start_radius:
			if Net.is_active():
				_go_to_game.rpc()
			else:
				_descend()
			return


@rpc("authority", "call_local", "reliable")
func _go_to_game() -> void:
	_descend()


func _descend() -> void:
	if _descending:
		return
	_descending = true
	WPlayer.input_blocked = true
	var layer := CanvasLayer.new(); layer.layer = 200; add_child(layer)
	var rect := ColorRect.new()
	rect.color = Color(0, 0, 0, 0)
	rect.set_anchors_preset(Control.PRESET_FULL_RECT)
	rect.mouse_filter = Control.MOUSE_FILTER_IGNORE
	layer.add_child(rect)
	if not AudioGen.is_headless():
		var rumble := AudioStreamPlayer.new()
		rumble.stream = load("res://assets/audio/sfx/crack_1_wood.ogg")
		rumble.volume_db = -2.0
		add_child(rumble)
		rumble.play()
	var t := create_tween()
	t.tween_property(rect, "color", Color(0, 0, 0, 1), descend_time)
	await t.finished
	await get_tree().create_timer(0.4).timeout
	get_tree().change_scene_to_file(GAME)
